version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "development-courier-locations"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1qaz@WSX"
    ports:
      - "5433:5432"
        
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1qaz@WSX
  
  courier-api:
    build:
      context: .                      
      dockerfile: CourierLocations.Api/Dockerfile
    container_name: courier-api
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=development-courier-locations;Username=admin;Password=1qaz@WSX"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__UserName: "admin"
      RabbitMQ__Password: "1qaz@WSX"
    ports:
      - "5074:8080" 